### PR TITLE
Corrected sentence and changed wait time.

### PR DESCRIPTION
**Pull request by Rich700000000000**
* Changed the sentence on line 88 so it reads better.
* Reduced the wait time from 10 minutes to 5 minutes, 10 minutes is way to long for 4chan.

### CODE REVIEW

**Comment by Lacsap-** [comment]
Looks good!

**Comment by Lacsap-** [comment]
Until I release a new version of 4scanner on pip you can:
- clone 4scanner
- ```virtualenv -p python3 env```
- ```source env/bin/activate```
- ``` python setup.py install```

This will install 4scanner with all change on the master branch inside a virtual python env

to get out of the virtualenv:
- ```deactivate```

**Comment by Rich700000000000** [comment]
Thanks! This is my first accepted pull request.

**Comment by Lacsap-** [comment]
Nice, congrats!

**Pull request merged**
