### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by ralic**
using : find . -name '*.py' | xargs 2to3 -w

### CODE REVIEW

**Comment by Lacsap-** [comment]
Hello,
Thanks for the pull request but I don't really understand the purpose. 4scanner is already written in python3.
All your commit did is add some parentheses in the print commands and break the travis tests (And maybe 4scanner, I didn't have a chance to test your changes)

Could you tell me what is the purpose of your changes are?

**Comment by ralic** [comment]
Just a few minor updates.. Thanks for comment !

**Comment by Lacsap-** [comment]
Travis tests are still in errors.

And you didn't answer me, what is the purpose of these changes?

**Comment by ralic** [comment]
I am referring to following link to not the same module name like the folder name to make code clear.

http://stackoverflow.com/questions/1250103/attributeerror-module-object-has-no-attribute .

**Comment by Lacsap-** [comment]
I'm sorry but you're saying you want to made the code clearer but you add binaries, log files, auto generated packaging files, and other random files into the repo.
You also added test for python 2.7 in travis but 4scanner does not even support it.

I can't merge this. This is anything but clearer. All this just for changing `scanner` to `scann` is really not worth it.

**Pull request closed without merging**
